Algoritmo TAREA3
	DEFINIR AREA,RADIO,PII Como Real;
	PII <-3.1416;
	ESCRIBIR "INTRODUCE EL RADIO DEL CIRCULO"
	LEER RADIO
	AREA<-RADIO*RADIO*PI
	ESCRIBIR "EL AREA DEL CIRCULO ES:",AREA
	
	
FinAlgoritmo
