Algoritmo TAREA2
	DEFINIR ALTURA Como Entero
	DEFINIR BASE Como Entero
	DEFINIR AREA Como Real
	ESCRIBIR "INTRODUCE LA ALTURA DEL TRIANGULO"
	LEER ALTURA
	ESCRIBIR "INTRODUCE LA BASE DEL TRIANGULO"
	LEER BASE
	AREA<-(BASE*ALTURA)/2
	ESCRIBIR "EL AREA ES :",AREA
FinAlgoritmo
