Algoritmo TAREA4
	DEFINIR NUM1,NUM2 Como Entero
	DEFINIR R Como Real
	ESCRIBIR "INTRODUCIR LOS NUMEROS"
	LEER NUM1,NUM2
	Si NUM1>NUM2 Entonces
		R<-NUM1/NUM2
		
	SiNo
		R<-NUM1/NUM2
	Fin Si
	ESCRIBIR "LA DIVISION ES =",R
	
FinAlgoritmo
